// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuQGt7YOecm5-P-fiau27Nc9SRztctwHQ',
    appId: '1:458618928116:web:5c130d0632596156c797a1',
    messagingSenderId: '458618928116',
    projectId: 'notes-wili',
    authDomain: 'notes-wili.firebaseapp.com',
    storageBucket: 'notes-wili.appspot.com',
    measurementId: 'G-1Z5V7G81JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANuhQRortOdxGgz090rtbmO_5QBr-38e4',
    appId: '1:458618928116:android:c43f929db1f65e51c797a1',
    messagingSenderId: '458618928116',
    projectId: 'notes-wili',
    storageBucket: 'notes-wili.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5vOoaLs2LILNeios-nFnWs83kmH-Syyg',
    appId: '1:458618928116:ios:a63d2f160a4fdfebc797a1',
    messagingSenderId: '458618928116',
    projectId: 'notes-wili',
    storageBucket: 'notes-wili.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5vOoaLs2LILNeios-nFnWs83kmH-Syyg',
    appId: '1:458618928116:ios:a63d2f160a4fdfebc797a1',
    messagingSenderId: '458618928116',
    projectId: 'notes-wili',
    storageBucket: 'notes-wili.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuQGt7YOecm5-P-fiau27Nc9SRztctwHQ',
    appId: '1:458618928116:web:1bdb725a7c8f86bbc797a1',
    messagingSenderId: '458618928116',
    projectId: 'notes-wili',
    authDomain: 'notes-wili.firebaseapp.com',
    storageBucket: 'notes-wili.appspot.com',
    measurementId: 'G-47VQ43NS37',
  );
}
