// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBptwodvgOb4dsSOXbZmSfcDzL-RC9u5Vc',
    appId: '1:152974950927:web:7cb1bd42d5e0ebe058d97a',
    messagingSenderId: '152974950927',
    projectId: 'notes-wilhy',
    authDomain: 'notes-wilhy.firebaseapp.com',
    storageBucket: 'notes-wilhy.appspot.com',
    measurementId: 'G-S9Y0NXRWH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDDcuOw5SvAdw-fsu4nATZe3jn7XoNoQ0',
    appId: '1:152974950927:android:e2b48b3f140a5afb58d97a',
    messagingSenderId: '152974950927',
    projectId: 'notes-wilhy',
    storageBucket: 'notes-wilhy.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEN9LUIkzutFjidKk5WTtCouArOWZaUc8',
    appId: '1:152974950927:ios:e53f4f11f691b7af58d97a',
    messagingSenderId: '152974950927',
    projectId: 'notes-wilhy',
    storageBucket: 'notes-wilhy.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEN9LUIkzutFjidKk5WTtCouArOWZaUc8',
    appId: '1:152974950927:ios:e53f4f11f691b7af58d97a',
    messagingSenderId: '152974950927',
    projectId: 'notes-wilhy',
    storageBucket: 'notes-wilhy.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBptwodvgOb4dsSOXbZmSfcDzL-RC9u5Vc',
    appId: '1:152974950927:web:6c5daad37501868d58d97a',
    messagingSenderId: '152974950927',
    projectId: 'notes-wilhy',
    authDomain: 'notes-wilhy.firebaseapp.com',
    storageBucket: 'notes-wilhy.appspot.com',
    measurementId: 'G-680C48QZX6',
  );
}
